public class SearchParameter {
    public Integer experience;
    public String[] service;
    public String language;
    public String[] foreignProficiency;
    public String[] englishProficiency;

    public Boolean isVerified;
    public String[] degree;
    public String zip;
    public Integer proximity;
    public Boolean citizenship;
    public String[] candidateRating;
    public Id bundleId;
    public Integer offset;
    public Integer resultSize;
    public Id locationId;
    public String searchByName;
    public String[] citizenshipValues;
    public Id languageId;
    public String countryOfbirth;
    public String sortingType;
    public String[] skillRating;
    public String[] instructorStatus;
    public String availabilityDate;
    public string bookmarkedUserId;
    public String[] languageIds;
    public Boolean dliQualified;
}