global class TaskDomain {
   
   /**********************************************************************
        Created by Vinitha on Aug 4 2017: Domain class used for TeamWork_Task And Teamwork_Sub_Task Object
        inner class formation
    ***********************************************************************/
    
    global class TaskInfo {
        
        global String Task_Name;
        global String ParentTask;
        global String TaskList;
        global Date DueDate;
        global String Priority;
        global String TeamworkLink;
        global String SalesforceLink;        
    }
}